version: "3.6"
services:
  db:
    image: postgres:10-alpine
    environment:
      POSTGRES_PASSWORD: oeq
      POSTGRES_USER: oeq
      POSTGRES_DB: oeq
  oeq:
    build:
      context: ./oeq/docker
      args:
        - OEQ_INSTALL_FILE=equella-installer-2020.1.3.zip
        - OEQ_INSTALL_ZIP_ROOT_DIR=equella-installer-2020.1.3
    environment:
      EQ_HTTP_PORT: 8080
      EQ_ADMIN_URL: "http://localhost:8080/admin"
      EQ_HIBERNATE_CONNECTION_URL: "jdbc:postgresql://db:5432/oeq"
      EQ_HIBERNATE_CONNECTION_USERNAME: "oeq"
      EQ_HIBERNATE_CONNECTION_PASSWORD: "oeq"
    depends_on:
      - db
    ports:
      - "8080:8080"
  mail:
    image: mailhog/mailhog:latest
